In [20]:
import pandas as pd

# Créez vos DataFrames
df_codes_postaux = pd.read_csv("Export_Données_Fournisseurs_MontantFactures.csv",sep=';')

df_departements_regions = pd.read_csv("regions_et_departements_francais.csv",sep=';')

# Extrait les deux premiers chiffres du code postal
df_codes_postaux['CodePostalPrefix'] = df_codes_postaux['shipping_postalcode'].str[:2]

# Fusionne les DataFrames sur les deux premiers chiffres du code postal
df_resultat = pd.merge(df_codes_postaux, df_departements_regions, left_on='CodePostalPrefix', right_on='NuméroDépartement', how='left')

# Affiche le résultat
print(df_resultat[['shipping_postalcode', 'Région']])

      shipping_postalcode                   Région
0                   68820                Grand Est
1                   68230                Grand Est
2                   90130  Bourgogne-Franche-Comté
3                   68360                Grand Est
4                   67730                Grand Est
...                   ...                      ...
79950               97500                      NaN
79951               97600                      NaN
79952               97600                      NaN
79953               97600                      NaN
79954               97615                      NaN

[79955 rows x 2 columns]

C:\Users\DELL\AppData\Local\Temp\ipykernel_11028\1624019266.py:5: DtypeWarning: Columns (16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_codes_postaux = pd.read_csv("Export_Données_Fournisseurs_MontantFactures.csv",sep=';')

In [10]:
import pandas as pd


# Créez vos DataFrames
df_codes_postaux = pd.read_csv("Export_Données_Fournisseurs_MontantFactures.csv",sep=';')

C:\Users\DELL\AppData\Local\Temp\ipykernel_11028\3967077754.py:5: DtypeWarning: Columns (16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df_codes_postaux = pd.read_csv("Export_Données_Fournisseurs_MontantFactures.csv",sep=';')

,name,email,phone,fax,siren,activity,naf_code,billing_address,billing_country,billing_postalcode,...,shipping_postalcode,created_at,already_called,company_size,relationship,favorite,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Arnold Fils (SARL),NaN,389822471,NaN,"3,253E+13",charpentes,4332A,22 r Croix,France,68820,...,68820,29/11/2021 19:36,0,Moyenne,0,NaN,NaN,NaN,NaN,NaN
1,Bianchi,NaN,389710288,NaN,"3,25338E+13",charpentes,4332A,3 r Fecht,France,68230,...,68230,29/11/2021 19:36,0,Petite,2,NaN,NaN,NaN,NaN,NaN
2,Binkert (SARL),NaN,384233802,NaN,"3,0202E+13",charpentes,4391A,41 Grande Rue,France,90130,...,90130,29/11/2021 19:36,0,Petite,2,NaN,NaN,NaN,NaN,NaN
3,Bois et Techniques,NaN,389533658,389265179,"5,01722E+13",charpentes,4391A,19 r Industrie,France,68360,...,68360,29/11/2021 19:36,NaN,NaN,0,0,NaN,NaN,NaN,NaN
4,Bois2boo,NaN,388855360,388855363,"4,93454E+13",charpentes,4391A,15 r Moulins,France,67730,...,67730,29/11/2021 19:36,NaN,NaN,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79950,NaN,NaN,508419000,NaN,NaN,travaux publics,NaN,9 RUE METIERS,France,97500,...,97500,27/11/2023 11:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79951,JUPITER HA SARL,NaN,NaN,NaN,"8,10484E+13",travaux publics,NaN,RUE DE L ARCHIPEL,France,97600,...,97600,27/11/2023 11:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79952,TRANSPORT CHADHULI,NaN,NaN,NaN,"2,40383E+12",travaux publics,NaN,NaN,France,97600,...,97600,27/11/2023 11:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79953,L'EFFICACITE,NaN,NaN,NaN,"5,00913E+13",travaux publics,NaN,15 RUE MANGA M KAKASSI,France,97600,...,97600,27/11/2023 11:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79954,GECKO BAT EURL,NaN,NaN,NaN,NaN,travaux publics,NaN,13 RUE MARIAME ALI M RARAYA,France,97615,...,97615,27/11/2023 11:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN